#!/usr/bin/env python3
from argparse import ArgumentParser, FileType
import sys


def main(argv=sys.argv[1:]):
    ap = ArgumentParser()
    ap.add_argument('-o', '--output', type=FileType(mode='w', encoding='utf-8'), required=True)
    ap.add_argument('input', nargs='+')

    args = ap.parse_args(argv)

    all_words = set()
    for path in args.input:
        with open(path, encoding='utf-8') as fin:
            for line in fin:
                word = line.strip()
                if not word[0].isupper() and "'" not in word:
                    all_words.add(line.strip())
    for word in sorted(all_words):
        print(word, file=args.output)


if __name__ == '__main__':
    main()